name: hl_ui
description: Theme-driven, accessible Flutter components for forms, feedback, and data states.
version: 1.0.2
homepage: https://github.com/iHanlei/flutter_hl_ui
repository: https://github.com/iHanlei/flutter_hl_ui.git

environment:
  sdk: ^3.9.0
  flutter: '>=3.35.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.1.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
